// file_mgr.rs — Read/write server.properties, eula.txt, and config files.

use std::fs;
use std::path::PathBuf;
use regex::Regex;

#[tauri::command]
pub fn read_properties(server_path: String) -> Result<String, String> {
    let path = PathBuf::from(&server_path).join("server.properties");
    if !path.exists() {
        return Ok("{}".to_string());
    }
    let content = fs::read_to_string(&path)
        .map_err(|e| format!("Failed to read server.properties: {e}"))?;
    let mut map = serde_json::Map::new();
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with('#') || line.is_empty() {
            continue;
        }
        if let Some((key, val)) = line.split_once('=') {
            map.insert(key.trim().to_string(), serde_json::Value::String(val.trim().to_string()));
        }
    }
    serde_json::to_string(&map).map_err(|e| format!("JSON error: {e}"))
}

#[tauri::command]
pub fn write_property(server_path: String, key: String, value: String) -> Result<(), String> {
    let path = PathBuf::from(&server_path).join("server.properties");
    let mut content = if path.exists() {
        fs::read_to_string(&path).map_err(|e| format!("Read error: {e}"))?
    } else {
        String::new()
    };
    let pattern = format!(r"(?m)^{}\s*=.*$", regex::escape(&key));
    let re = Regex::new(&pattern).map_err(|e| format!("Regex error: {e}"))?;
    let replacement = format!("{key}={value}");
    if re.is_match(&content) {
        content = re.replace(&content, replacement.as_str()).to_string();
    } else {
        if !content.ends_with('\n') && !content.is_empty() {
            content.push('\n');
        }
        content.push_str(&replacement);
        content.push('\n');
    }
    fs::write(&path, content).map_err(|e| format!("Write error: {e}"))
}

#[tauri::command]
pub fn write_eula(server_path: String) -> Result<(), String> {
    let path = PathBuf::from(&server_path).join("eula.txt");
    let content = "# Generated by EasyServe\n# https://www.minecraft.net/en-us/eula\neula=true\n";
    fs::write(&path, content).map_err(|e| format!("Failed to write eula.txt: {e}"))
}

#[tauri::command]
pub fn create_server_dir(server_path: String) -> Result<(), String> {
    let path = PathBuf::from(&server_path);
    fs::create_dir_all(&path).map_err(|e| format!("Failed to create dir: {e}"))?;
    fs::create_dir_all(path.join("plugins")).map_err(|e| format!("Failed to create plugins dir: {e}"))
}
